title: Perdana & Code
description: Unlimited Code Works
author: Perdana Hadi Sanjaya
github: https://github.com/ceroberoz
about: Full Stack Backend Developer, Linux Enthusiast & Experimental Developer
disqus_shortname: perdanahadisanjaya
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/ceropyon"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/perdana-hadi-sanjaya-6079b652"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/ceroberoz"

share:
  twitter_username: ceropyon
  fb_appid: "#"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://blog-54a45.firebaseapp.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
